plugins {
    id 'java-library'
    id 'org.jetbrains.kotlin.jvm' version '2.0.0'
}

repositories {
    google()
    mavenCentral()
}

java {
    sourceCompatibility JavaVersion.VERSION_17
    targetCompatibility JavaVersion.VERSION_17
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation gradleApi()//gradle sdk
    implementation localGroovy()//groovy sdk

    api 'org.codehaus.groovy:groovy-xml:3.0.9'
    api 'com.squareup:javapoet:1.13.0'
    compileOnly 'com.android.tools.build:gradle:8.10.1'
}
